-- =========================================================
-- TFM - Esquema de base de datos
-- Versión: v0.10
-- Fecha: 26/08/2026
-- =========================================================

-- Extensión necesaria para embeddings vectoriales
create extension if not exists vector with schema extensions;

-- =========================================================
-- PERFILES
-- =========================================================

create table public.perfiles (
    id bigint generated by default as identity primary key,
    nombre text not null,
    intereses text,
    aficiones text,
    preferencias text,
    perfil_completo boolean default false,
    creado_en timestamptz default now()
);

-- =========================================================
-- ACTIVIDADES
-- =========================================================

create table public.actividades (
    id bigint generated by default as identity primary key,
    perfil_id bigint not null
        references public.perfiles(id)
        on delete cascade,

    objetivo_aprendizaje text not null,
    tema text,
    dificultad text,
    contenido text,

    tipo_actividad text default 'normal',

    actividad_origen_id bigint
        references public.actividades(id),

    interes_personalizacion text,
    referencias_rag jsonb,
    resultado_guardrails jsonb,

    regeneraciones integer default 0,
    estado text default 'pendiente',

    creado_en timestamptz default now()
);

-- =========================================================
-- INTENTOS
-- =========================================================

create table public.intentos (
    id bigint generated by default as identity primary key,

    actividad_id bigint not null
        references public.actividades(id)
        on delete cascade,

    numero_intento integer default 1,

    fecha_inicio timestamptz,
    fecha_fin timestamptz,
    tiempo_segundos integer,

    puntuacion_obtenida numeric(5,2),
    puntuacion_maxima numeric(5,2) default 10,

    finalizada boolean default false,
    errores text,

    creado_en timestamptz default now()
);

-- =========================================================
-- DOCUMENTOS RAG
-- =========================================================

create table public.documentos_rag (
    id bigint generated by default as identity primary key,
    text text not null,
    metadata jsonb default '{}'::jsonb,
    embedding extensions.vector(1536),

    material_id bigint
        references public.materiales_docentes(id)
        on delete cascade,

    creado_en timestamptz default now()
);

-- =========================================================
-- FUNCIÓN DE BÚSQUEDA VECTORIAL
-- =========================================================

create or replace function public.match_documentos_rag(
    query_embedding extensions.vector(1536),
    match_count int default 5
)
returns table (
    id bigint,
    text text,
    metadata jsonb,
    similarity float
)
language sql
stable
as $$
    select
        documentos_rag.id,
        documentos_rag.text,
        documentos_rag.metadata,
        1 - (
            documentos_rag.embedding <=> query_embedding
        ) as similarity
    from public.documentos_rag
    where documentos_rag.embedding is not null
    order by
        documentos_rag.embedding <=> query_embedding
    limit match_count;
$$;
-- =========================================================
-- materiales docentes
-- =========================================================

create table public.materiales_docentes (
    id bigint generated by default as identity primary key,
    titulo text not null,
    tema text,
    fuente text,
    texto_original text not null,
    texto_normalizado text not null,
    numero_chunks integer not null default 0,
    estado text not null default 'activo',
    creado_en timestamptz default now()
);

create index idx_documentos_rag_material_id
on public.documentos_rag(material_id);